### ISSUE TITLE
Refatorar retorno dos dados de usuário'

### ISSUE THREAD

**Issue by BerkSpar** [BerkSpar/sig-api#1]
## Descrição
Necessita trazer dados de forma mais concisas. 

## Dados

- [x] Aluno especial para **boleano**
- [x] CRE trocar vírgula por ponto
- [x] Remover "º" (Período referencia e período ingresso)
- [ ] Aplicar valores null quando "-"
- [x] Cota sistec e cota mec para **boleano**

**Comment by uelpin** [comment]
Criar função para normalizar o objeto. ex : Aplicar valores null quando "-"
